# swagger.yml
#file that specifies metadata about an API using the OpenAPI specification version 3.0.0.

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"
  
#define the root path of your API
servers:
  - url: "/api"
  
#define your API endpoints
paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
